// Generated by prepare.py from current production source; do not edit.
using System; using System.Collections.Generic; using System.Linq;
using UnityEngine; using Nyangbingo.Core; using Nyangbingo.Data; using Nyangbingo.Bosses;
partial class EncounterFixture {
        private bool IsDayEventNight => bootstrap?.TimeService?.IsNight == true &&
            gameDataCatalog != null && gameDataCatalog.DayEvents.Any(e => e != null && e.Day == bootstrap.TimeService.Day);
        public bool IsRegularSpawningEnabled => regularSpawningEnabled && !discardRegularForCurrentNight &&
            !IsDayEventNight;
        public static bool ShouldDiscardLegacyEarlyGaekgwi(bool dayEventNight, bool raid,
            YokaiKind kind, int dispatchedWaves) =>
            dayEventNight && !raid && kind == YokaiKind.Gaekgwi && dispatchedWaves < 2;
        public void HandleNightStart()
        {
            discardRegularForCurrentNight = false;
            regularSpawningEnabled = baekjungScheduler?.IsActive != true;
            ClearPendingRegular();
            var day = bootstrap != null && bootstrap.TimeService != null ? bootstrap.TimeService.Day : 0;
            currentDayCurve = gameDataCatalog.FindDayCurve(day);

            // Restore rebuilds event subscriptions, so the regular handler can run before
            // the Baekjung handler. The calendar, not callback order, owns this night.
            if (currentDayCurve == null || IsDayEventNight) return;

            var includesForcedInvasionBoss = TryGetForcedInvasionCompositionKind(
                day, out var forcedInvasionKind);
            var composition = currentDayCurve.SpawnComposition;
            for (var groupIndex = 0; groupIndex < composition.Length; groupIndex++)
            {
                var group = composition[groupIndex];
                var definition = gameDataCatalog.Yokai.FirstOrDefault(candidate =>
                    candidate != null && candidate.Kind == group.kind &&
                    candidate.SupportsSpawnTrack(YokaiSpawnTrack.Raid));
                var amount = Math.Max(0, group.amount);
                if (includesForcedInvasionBoss && group.kind == forcedInvasionKind)
                    amount = Math.Max(0, amount - 1);
                for (var count = 0; definition != null && count < amount; count++)
                    EnqueuePendingRegular(definition);
            }
            TryFillRegularSlots();
        }
}
partial class TileFixture {
        public bool TryGetYokaiSpawnPosition(Vector3Int feetCell, float radius, out Vector3 position)
        {
            position = default;
            if (float.IsNaN(radius) || float.IsInfinity(radius) || radius <= 0f ||
                !InBounds(feetCell) || !InBounds(feetCell + Vector3Int.down)) return false;
            var floor = feetCell + Vector3Int.down;
            if (!GetTile(floor).BlocksMovement || IsDoorOpen(floor)) return false;
            var feetBounds = GetCellWorldBounds(feetCell);
            var center = new Vector2(feetBounds.center.x, feetBounds.min.y + radius + .02f);
            var min = WorldToCell(center - Vector2.one * radius);
            var max = WorldToCell(center + Vector2.one * radius);
            for (var x = min.x; x <= max.x; x++)
                for (var y = min.y; y <= max.y; y++)
                {
                    var cell = new Vector3Int(x, y, feetCell.z);
                    if (!InBounds(cell)) return false;
                    if (!GetTile(cell).BlocksMovement || IsDoorOpen(cell)) continue;
                    var bounds = GetCellWorldBounds(cell);
                    var closest = new Vector2(Mathf.Clamp(center.x, bounds.min.x, bounds.max.x),
                        Mathf.Clamp(center.y, bounds.min.y, bounds.max.y));
                    if ((center - closest).sqrMagnitude < radius * radius) return false;
                }
            position = new Vector3(center.x, center.y, feetBounds.center.z);
            return true;
        }
}
