from pathlib import Path
import sys

root = Path(__file__).resolve().parents[4]
dest = Path(__file__).resolve().parent
encounter = (root / 'Assets/Scripts/Nyangbingo/World/MainGameEncounterCoordinator.cs').read_text(encoding='utf-8-sig')
tiles = (root / 'Assets/Scripts/Nyangbingo/World/TileService.cs').read_text(encoding='utf-8-sig')

def method(source, signature):
    start = source.index(signature)
    opening = source.index('{', start)
    depth = 1
    end = opening + 1
    while depth:
        depth += (source[end] == '{') - (source[end] == '}')
        end += 1
    return source[start:end]

properties = encounter[encounter.index('        private bool IsDayEventNight'):encounter.index('        public BossManager BossManager')]
legacy = encounter[encounter.index('        public static bool ShouldDiscardLegacyEarlyGaekgwi'):encounter.index('        public static bool ShouldSpawnResident')]
handler = method(encounter, '        private void HandleNightStart()').replace('private void', 'public void', 1)
if '--legacy' in sys.argv:
    # Negative control: reproduce the previous callback-order-dependent gate.
    properties = properties.replace(' &&\n            !IsDayEventNight', '')
    handler = handler.replace('currentDayCurve == null || IsDayEventNight', 'currentDayCurve == null')
spawn = method(tiles, '        public bool TryGetYokaiSpawnPosition')
(dest / 'Extracted.cs').write_text('''// Generated by prepare.py from current production source; do not edit.
using System; using System.Collections.Generic; using System.Linq;
using UnityEngine; using Nyangbingo.Core; using Nyangbingo.Data; using Nyangbingo.Bosses;
partial class EncounterFixture {
''' + properties + legacy + handler + '\n}\npartial class TileFixture {\n' + spawn + '\n}\n', encoding='utf-8')
