using Nyangbingo.Data;
using Nyangbingo.Core;
var checks=0;
void Check(bool value,string name){if(!value)throw new Exception(name);checks++;}
ItemDefinition Item(string id,string name)=>new(){Id=id,DisplayName=name};
ItemAmount Amount(ItemDefinition i,int n=1)=>new(){item=i,amount=n};
var c=new GameDataCatalog();
var ore=Item("iron_ore","철 광석");var ingot=Item("iron_ingot","철 주괴");var coal=Item("coal","석탄");var shard=Item("club_shard","조각");var bundle=Item("stolen_bundle","보따리");var pearl=Item("yeouiju","여의주");
c.MineralTiers.Add(new(){Resource=ore,Layer=MineralLayer.UndergroundMiddle,MinimumDepth=46,MaximumDepth=90,MinimumClawTier=1,Hardness=1});
var text=MaterialSourceGuide.Describe(c,ore.Id);
Check(text.Contains("채집 · 지하 중층"),"mineral category");Check(text.Contains("46~90칸"),"depth");Check(text.Contains("T1 (경도 1)"),"soft gate keeps T1");
c.MineralTiers[0].Hardness=3;Check(MaterialSourceGuide.Describe(c,ore.Id).Contains("T3"),"hardness gate");
c.Yokai.Add(new(){DisplayName="방망이 도깨비",SignatureItem=shard,SignatureChance=.25f,SpawnTracks=YokaiSpawnTrack.Raid});
text=MaterialSourceGuide.Describe(c,shard.Id);
Check(text.Contains("25% · 매번 나오지 않음"),"random drop wording");Check(text.Contains("방망이 도깨비 · 밤"),"name and night");Check(!text.Contains("확정"),"not guaranteed");
c.Yokai.Add(new(){DisplayName="야광귀",SignatureItem=bundle,SignatureChance=1f,SignatureCondition=YokaiSignatureCondition.StealSuccess,SpawnTracks=YokaiSpawnTrack.Raid});
text=MaterialSourceGuide.Describe(c,bundle.Id);Check(text.Contains("확정 · 절도 성공 후 처치 시"),"conditional guarantee");
c.Yokai.Add(new(){DisplayName="이무기",SignatureItem=shard,SignatureChance=.4f,SpawnTracks=YokaiSpawnTrack.Resident});Check(MaterialSourceGuide.Describe(c,shard.Id).Contains("이무기 · 상주"),"resident and multiple sources");
c.Bosses.Add(new(){DisplayName="강철이",GuaranteedDrops=new[]{Amount(pearl)}});Check(MaterialSourceGuide.Describe(c,pearl.Id).Contains("강철이 · 격파 시 확정"),"corrected boss identity");
c.Smelting.Add(new(){Input=Amount(ore,2),Fuel=Amount(coal),Output=Amount(ingot),StationKind=SmeltingStationKind.Furnace});
text=MaterialSourceGuide.Describe(c,ingot.Id);Check(text.Contains("제련 · 화로"),"smelting station");Check(text.Contains("철 광석 ×2 · 연료: 석탄 ×1"),"smelting materials");
c.Recipes.Add(new(){Output=Amount(ingot),Station=CraftingStation.Workbench,Ingredients=new[]{Amount(ore,3)}});Check(MaterialSourceGuide.Describe(c,ingot.Id).Contains("제작 · 작업대"),"crafted source");
c.Recipes[0].MvpScope=ItemMvpScope.B;Check(!MaterialSourceGuide.Describe(c,ingot.Id).Contains("제작 · 작업대"),"hidden B recipe");
c.Crops.Add(new(){CropId="catnip",ZoneId="zone01",Order=1,SpawnPerHundredTiles=3});c.Zones.Add(new(){Id="zone01",DistanceTilesFrom=0,DistanceTilesTo=100});
c.TerrainSpawns.Add(new(){Implemented=true,TerrainDisplayName="숲",TerrainResourceIds=new[]{"catnip","mushroom"}});
c.TerrainSpawns.Add(new(){Implemented=true,TerrainDisplayName="숲",TerrainResourceIds=new[]{"catnip"}});
text=MaterialSourceGuide.Describe(c,"catnip");Check(text.Contains("작물 채집 · 밴드 1 · 거점에서 0~100칸"),"crop band");Check(text.Contains("지형: 숲")&&!text.Contains("숲 · 숲"),"deduplicate terrain");
Check(MaterialSourceGuide.Describe(c,"mushroom").Contains("채집 지형 · 숲"),"terrain-only source");Check(MaterialSourceGuide.Describe(c,"unknown").Contains("등록되어 있지"),"unknown does not invent");Check(MaterialSourceGuide.Describe(null,"unknown").Contains("확인할 수 없어요"),"null catalog");
Console.WriteLine($"S6 CPU source checks: {checks}/{checks} passed. No Unity runtime executed.");
